### ISSUE TITLE
Offering to (co-)maintain the Migrate module

### ISSUE THREAD

**Issue by oadaeh** [backdrop-contrib/migrate#1]
Hello.

I am interested in getting a working port of this module for Backdrop, with the intention of also porting the [Drupal-to-Drupal data migration](https://www.drupal.org/project/migrate_d2d) (renamed to Drupal-to-Backdrop data migration) and [WordPress Migrate](https://www.drupal.org/project/wordpress_migrate) modules.

I am also willing to (co-)maintain this for the foreseeable future.

**Comment by klonos** [comment]
Enough time has passed since this was posted, and the initial module porter/maintainer has not replied. @oadaeh please feel free to take over and add your name to the maintainers list of this project 👍

**Comment by oadaeh** [comment]
Done.
